[package]
name = "tyres"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
parser = { path = "../parser"}
call_chain = { path = "../call_chain"}
variables = { path = "../variables"}
ast = { path = "../ast"}
my_string = { path = "../my_string"}
workspace_hack = { version = "0.1", path = "../workspace_hack" }
