[package]
name = "loader"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
parser.workspace = true
ast.workspace = true
my_string.workspace = true
jwalk.workspace = true
rc-zip-tokio.workspace = true
postcard.workspace = true
rayon.workspace = true
tokio.workspace = true
memmap2.workspace = true
workspace_hack = { version = "0.1", path = "../workspace_hack" }
