[package]
name = "position"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
lsp-types.workspace = true
ast = { path = "../ast"}
lsp_extra = { path = "../lsp_extra"}
workspace_hack = { version = "0.1", path = "../workspace_hack" }

[dev-dependencies]
pretty_assertions.workspace = true
