[package]
name = "server"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true
lsp-server.workspace = true
lsp-types.workspace = true
dashmap.workspace = true
serde_json.workspace = true
rayon.workspace = true
jwalk.workspace = true
format = { path = "../format"}
parser = { path = "../parser"}
loader = { path = "../loader"}
maven = { path = "../maven"}
gradle = { path = "../gradle"}
imports = { path = "../imports"}
tyres = { path = "../tyres"}
position = { path = "../position"}
document = { path = "../document"}
variables = { path = "../variables"}
jdk = { path = "../jdk"}
compile = { path = "../compile"}
call_chain = { path = "../call_chain" }
common = { path = "../common"}
ast = { path = "../ast"}
get_class = { path = "../get_class"}
my_string = { path = "../my_string"}
lsp_extra = { path = "../lsp_extra"}

[dev-dependencies]
pretty_assertions.workspace = true
