[package]
name = "gradle"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
my_string = { path = "../my_string"}
compile = {path = "../compile"}
common = {path = "../common"}
parser = {path = "../parser"}
loader = {path = "../loader"}
maven = {path = "../maven"}
workspace_hack = { version = "0.1", path = "../workspace_hack" }

[dev-dependencies]
pretty_assertions.workspace = true
