[package]
name = "jdk"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
dirs.workspace = true
my_string = { path = "../my_string"}
parser = { path = "../parser" }
loader = {path = "../loader"}
zip_util = { path = "../zip_util" }
common = { path = "../common" }
workspace_hack = { version = "0.1", path = "../workspace_hack" }

[dev-dependencies]
pretty_assertions.workspace = true
