[package]
name = "java_lsp"
version = "0.1.0"
edition.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
tokio.workspace = true
document = { path = "../document" }
variables = { path = "../variables" }
cli = { path = "../cli" }
server = { path = "../server" }
common = { path = "../common" }
format = { path = "../format" }
jdk = { path = "../jdk"}
workspace_hack = { version = "0.1", path = "../workspace_hack" }
