[package]
name = "maven"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs.workspace = true
tokio.workspace = true
sha1_smol.workspace = true
reqwest.workspace = true
serde.workspace = true
serde-xml-rs.workspace = true
my_string = { path = "../my_string"}
common = { path = "../common" }
parser = {path = "../parser"}
loader = {path = "../loader"}
zip_util = { path = "../zip_util" }
workspace_hack = { version = "0.1", path = "../workspace_hack" }

[dev-dependencies]
pretty_assertions.workspace = true
