[package]
name = "variables"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
parser = {path = "../parser"}
my_string = { path = "../my_string"}
ast = {path = "../ast"}
workspace_hack = { version = "0.1", path = "../workspace_hack" }

[dev-dependencies]
insta.workspace = true
