[package]
name = "server"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true
lsp-server.workspace = true
lsp-types.workspace = true
serde_json.workspace = true
rayon.workspace = true
jwalk.workspace = true
format.workspace = true
parser.workspace = true
loader.workspace = true
maven.workspace = true
gradle.workspace = true
imports.workspace = true
tyres.workspace = true
position.workspace = true
document.workspace = true
variables.workspace = true
jdk.workspace = true
compile.workspace = true
call_chain.workspace = true
common.workspace = true
ast.workspace = true
get_class.workspace = true
my_string.workspace = true
lsp_extra.workspace = true
workspace_hack = { version = "0.1", path = "../workspace_hack" }

[dev-dependencies]
pretty_assertions.workspace = true
